export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RESET = 'RESET';

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_USER= "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const GET_ROLE = "GET_ROLE";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_ERROR = "GET_ROLE_ERROR";

export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS";
export const GET_ALL_ROLES_ERROR = "GET_ALL_ROLES_ERROR";

export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
export const GET_ALL_PERMISSIONS_SUCCESS = "GET_ALL_PERMISSIONS_SUCCESS";
export const GET_ALL_PERMISSIONS_ERROR = "GET_ALL_PERMISSIONS_ERROR";

export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";
export const GET_ROLE_PERMISSIONS_SUCCESS = "GET_ROLE_PERMISSIONS_SUCCESS";
export const GET_ROLE_PERMISSIONS_ERROR = "GET_ROLE_PERMISSIONS_ERROR";

export const CREATE_ROLE_PERMISSIONS = "CREATE_ROLE_PERMISSIONS";
export const CREATE_ROLE_PERMISSIONS_SUCCESS = "CREATE_ROLE_PERMISSIONS_SUCCESS";
export const CREATE_ROLE_PERMISSIONS_ERROR = "CREATE_ROLE_PERMISSIONS_ERROR";