export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_USER= "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const CREATE_USER = "CREATE_USER";

export const GET_ROLE = "GET_ROLE";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_ERROR = "GET_ROLE_ERROR";

export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS";
export const GET_ALL_ROLES_ERROR = "GET_ALL_ROLES_ERROR";

export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
export const GET_ALL_PERMISSIONS_SUCCESS = "GET_ALL_PERMISSIONS_SUCCESS";
export const GET_ALL_PERMISSIONS_ERROR = "GET_ALL_PERMISSIONS_ERROR";

export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";
export const GET_ROLE_PERMISSIONS_SUCCESS = "GET_ROLE_PERMISSIONS_SUCCESS";
export const GET_ROLE_PERMISSIONS_ERROR = "GET_ROLE_PERMISSIONS_ERROR";

export const CREATE_ROLE_PERMISSIONS = "CREATE_ROLE_PERMISSIONS";
export const CREATE_ROLE_PERMISSIONS_SUCCESS = "CREATE_ROLE_PERMISSIONS_SUCCESS";
export const CREATE_ROLE_PERMISSIONS_ERROR = "CREATE_ROLE_PERMISSIONS_ERROR";

export const UPDATE_ROLE_PERMISSIONS = "UPDATE_ROLE_PERMISSIONS";
export const UPDATE_ROLE_PERMISSIONS_SUCCESS = "UPDATE_ROLE_PERMISSIONS_SUCCESS";
export const UPDATE_ROLE_PERMISSIONS_ERROR = "UPDATE_ROLE_PERMISSIONS_ERROR";

export const DELETE_ROLES_AND_PERMISSIONS = "DELETE_ROLES_AND_PERMISSIONS";
export const DELETE_ROLES_AND_PERMISSIONS_SUCCESS = "DELETE_ROLES_AND_PERMISSIONS_SUCCESS";
export const DELETE_ROLES_AND_PERMISSIONS_ERROR = "DELETE_ROLES_AND_PERMISSIONS_ERROR";

export const GET_ALL_SERVICEMEN = "GET_ALL_SERVICEMEN";
export const GET_ALL_SERVICEMEN_SUCCESS = "GET_ALL_SERVICEMEN_SUCCESS";
export const GET_ALL_SERVICEMEN_ERROR = "GET_ALL_SERVICEMEN_ERROR";

export const GET_SERVICEMAN = "GET_SERVICEMAN";
export const GET_SERVICEMAN_SUCCESS = "GET_SERVICEMAN_SUCCESS";
export const GET_SERVICEMAN_ERROR = "GET_SERVICEMAN_ERROR";

export const APPROVE_SERVICEMAN = "APPROVE_SERVICEMAN";
export const APPROVE_SERVICEMAN_SUCCESS = "APPROVE_SERVICEMAN_SUCCESS";
export const APPROVE_SERVICEMAN_ERROR = "APPROVE_SERVICEMAN_ERROR";

export const REJECT_SERVICEMAN = "REJECT_SERVICEMAN";
export const REJECT_SERVICEMAN_SUCCESS = "REJECT_SERVICEMAN_SUCCESS";
export const REJECT_SERVICEMAN_ERROR = "REJECT_SERVICEMAN_ERROR";

export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS";
export const GET_ALL_JOBS_ERROR = "GET_ALL_JOBS_ERROR";

export const GET_PENDING_JOBS = "GET_PENDING_JOBS";
export const GET_PENDING_JOBS_SUCCESS = "GET_PENDING_JOBS_SUCCESS";
export const GET_PENDING_JOBS_ERROR = "GET_PENDING_JOBS_ERROR";

export const GET_ACTIVE_JOBS = "GET_ACTIVE_JOBS";
export const GET_ACTIVE_JOBS_SUCCESS = "GET_ACTIVE_JOBS_SUCCESS";
export const GET_ACTIVE_JOBS_ERROR = "GET_ACTIVE_JOBS_ERROR";

export const GET_SCHEDULED_JOBS = "GET_SCHEDULED_JOBS";
export const GET_SCHEDULED_JOBS_SUCCESS = "GET_SCHEDULED_JOBS_SUCCESS";
export const GET_SCHEDULED_JOBS_ERROR = "GET_SCHEDULED_JOBS_ERROR";

export const GET_COMPLETED_JOBS = "GET_COMPLETED_JOBS";
export const GET_COMPLETED_JOBS_SUCCESS = "GET_COMPLETED_JOBS_SUCCESS";
export const GET_COMPLETED_JOBS_ERROR = "GET_COMPLETED_JOBS_ERROR";

export const GET_DECLINED_JOBS = "GET_DECLINED_JOBS";
export const GET_DECLINED_JOBS_SUCCESS = "GET_DECLINED_JOBS_SUCCESS";
export const GET_DECLINED_JOBS_ERROR = "GET_DECLINED_JOBS_ERROR";

export const GET_REJECTED_JOBS = "GET_REJECTED_JOBS";
export const GET_REJECTED_JOBS_SUCCESS = "GET_REJECTED_JOBS_SUCCESS";
export const GET_REJECTED_JOBS_ERROR = "GET_REJECTED_JOBS_ERROR";

export const GET_JOB_DETAILS = "GET_JOB_DETAILS";
export const GET_JOB_DETAILS_SUCCESS = "GET_JOB_DETAILS_SUCCESS";
export const GET_JOB_DETAILS_ERROR = "GET_JOB_DETAILS_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

export const UPDATE_CATEGORY_STATUS = "UPDATE_CATEGORY_STATUS";
export const UPDATE_CATEGORY_STATUS_SUCCESS = "UPDATE_CATEGORY_STATUS_SUCCESS";
export const UPDATE_CATEGORY_STATUS_ERROR = "UPDATE_CATEGORY_STATUS_ERROR";

export const GET_SUB_CATEGORY_AND_SERVICES = "GET_SUB_CATEGORY_AND_SERVICES";
export const GET_SUB_CATEGORY_AND_SERVICES_SUCCESS = "GET_SUB_CATEGORY_AND_SERVICES_SUCCESS";
export const GET_SUB_CATEGORY_AND_SERVICES_ERROR = "GET_SUB_CATEGORY_AND_SERVICES_ERROR";

export const UPDATE_SUB_CATEGORY_STATUS = "UPDATE_SUB_CATEGORY_STATUS";
export const UPDATE_SUB_CATEGORY_STATUS_SUCCESS = "UPDATE_SUB_CATEGORY_STATUS_SUCCESS";
export const UPDATE_SUB_CATEGORY_STATUS_ERROR = "UPDATE_SUB_CATEGORY_STATUS_ERROR";

export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_ERROR = "GET_SERVICES_ERROR";

export const UPDATE_SERVICES_STATUS = "UPDATE_SERVICES_STATUS";
export const UPDATE_SERVICES_STATUS_SUCCESS = "UPDATE_SERVICES_STATUS_SUCCESS";
export const UPDATE_SERVICES_STATUS_ERROR = "UPDATE_SERVICES_STATUS_ERROR";