import * as React from "react";
import '../styles/globals.css';
import 'rsuite/dist/rsuite.min.css';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { useStore } from '../state';

function MyApp({ Component, pageProps }) {
    const store = useStore();
  return  (
        <div>
          <Head>
            <title>Geal Admin</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="initial-scale=1, width=device-width" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            <Provider store={store}>
                <Component {...pageProps} />
            </Provider>
        </div>
      )

}

export default MyApp
