import * as React from "react";
import { CustomProvider } from 'rsuite';
import '../styles/globals.css';
import "react-multi-carousel/lib/styles.css";
import 'rsuite/dist/rsuite.min.css';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { useStore } from '../state';

function MyApp({ Component, pageProps }) {
    const store = useStore();
  return  (
        <div>
          <Head>
            <title>Quickfix-SI</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="initial-scale=1, width=device-width" />
            <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <CustomProvider themes="dark">
            <Provider store={store}>
                <Component {...pageProps} />
            </Provider>
            </CustomProvider>
        </div>
      )

}

export default MyApp
