import * as React from 'react';
import { useDispatch } from 'react-redux';
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import CssBaseline from '@mui/material/CssBaseline';
import TextField from '@mui/material/TextField';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Link from '@mui/material/Link';
import { useRouter } from "next/router";
import Paper from '@mui/material/Paper';
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import LockOutlinedIcon from '@mui/icons-material/LockOutlined';
import Typography from '@mui/material/Typography';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import Head from 'next/head'
import {loginUser} from "../state/actions/userLoginAction";
import {getRoles} from "../state/actions/roleAction";


function Copyright(props) {
  return (
    <Typography variant="body2" color="text.secondary" align="center" {...props}>
      {'Copyright © '}
      <Link color="inherit" href="https://material-ui.com/">
        Your Website
      </Link>{' '}
      {new Date().getFullYear()}
      {'.'}
    </Typography>
  );
}

const theme = createTheme();

export default function Home() {
    const router = useRouter();
    const dispatch = useDispatch();
    const [loginDetails, setLoginDetails] = React.useState({
        phone: '',
        password: '',
    });
    const [loginStatus, setLoginStatus] = React.useState({
        error: '',
        loading: false,
    });

    const handleUserLogin = e => {
        setLoginStatus(status => ({
            ...status,
            loading: true,
            error: '',
        }));
        e.preventDefault();
        const { phone, password } = loginDetails;

        const bodyData = {
            phone,
            password,
        };

        loginUser(dispatch, bodyData).then(response => {
            console.log(response);
            if (response.status === 200) router.push('/dashboard/home', undefined, {shallow: true});
            if (response.status === 401)setLoginStatus({ loading: false, error: response.message });
        });
    };

    const handleInputChange = e => {
        e.persist();
        setLoginDetails(details => ({
            ...details,
            [e.target.name]: e.target.value,
        }));
    };

    React.useEffect(() => {
        const user = localStorage.currentUser && JSON.parse(localStorage.currentUser);
        if (user){
            router.push('/dashboard/home');
        } else {
            localStorage.clear();
        }
    }, [dispatch, router]);
  return (
    <div>
      <Head>
        <title>Geal Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <ThemeProvider theme={theme}>
      <Grid container component="main" sx={{ height: '100vh' }}>
        <CssBaseline />
        <Grid
          item
          xs={false}
          sm={4}
          md={8}
          sx={{
            backgroundImage: 'url(https://professors.toprated.co.ke/_next/static/images/login-73768b9025c008203f404815155f7499.svg)',
            backgroundRepeat: 'no-repeat',
            backgroundColor: (t) =>
              t.palette.mode === 'light' ? t.palette.grey[50] : t.palette.grey[900],
            backgroundSize: 'cover',
            backgroundPosition: 'center',
          }}
        >
            <Box sx={{ml: 5, color: '#1976D2', '@media only screen and (max-width: 600px)': {display: 'none'}}}>
                <h1>Geal Admin</h1>
            </Box>
      </Grid>
        <Grid item xs={12} sm={8} md={4} component={Paper} elevation={6} square>
          <Box
            sx={{
              my: 8,
              mx: 4,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
            <Avatar sx={{ m: 1, bgcolor: '#1796D2' }}>
              <LockOutlinedIcon />
            </Avatar>
            <Typography component="h1" variant="h5">
                <center>
                    Welcome to Geal Admin! 👋 <br/>
                    Sign in
                </center>
            </Typography>
              {loginStatus.error && (
                  <Alert severity="error">{loginStatus.error }</Alert>
              )}
            <Box component="form" noValidate onSubmit={handleUserLogin} sx={{ mt: 1 }}>
              <TextField
                margin="normal"
                required
                fullWidth
                id="phone"
                label="Phone Number"
                name="phone"
                autoComplete="phone"
                autoFocus
                value={loginDetails.email}
                onChange={handleInputChange}
              />
              <TextField
                margin="normal"
                required
                fullWidth
                name="password"
                label="Password"
                type="password"
                id="password"
                autoComplete="current-password"
                value={loginDetails.password}
                onChange={handleInputChange}
              />
              <FormControlLabel
                control={<Checkbox value="remember" color="primary" />}
                label="Remember me"
              />
              <Button
                type="submit"
                fullWidth
                variant="contained"
                sx={{ mt: 3, mb: 2 }}
              >
                Sign In
              </Button>
              <Grid container>
                <Grid item xs>
                  <Link href="#" variant="body2">
                    Forgot password?
                  </Link>
                </Grid>
                <Grid item>
                    <Box sx={{cursor: 'pointer', color: '#1796D2'}} onClick={() => router.push('/user/register',  undefined, { shallow: true})}>
                        Don&sbquo;t have an account? Sign Up
                    </Box>
                </Grid>
              </Grid>
              <Copyright sx={{ mt: 5 }} />
            </Box>
          </Box>
        </Grid>
      </Grid>
    </ThemeProvider>
      </main>
    </div>
  )
}
