import React from 'react';
import {Navbar, Nav, Button, Panel, Carousel, ButtonToolbar, Dropdown, Divider} from 'rsuite';
import Footer from "../components/dashboard/home/footer";
import { useRouter } from "next/router";
import CheckOutlineIcon from '@rsuite/icons/CheckOutline';
import Image from "next/image";
import Repair from '../assets/repair.png';
import Electrical from '../assets/electrical.png';
import Washing from '../assets/washing.png';
import Cooker from '../assets/cooker.png';
import Dishwasher from '../assets/dishwasher.png';
import Boiler from '../assets/boiler.png';
import Cooler from '../assets/cooler.png';
import Oven from '../assets/oven.png';
import tumbDryer from '../assets/tumbldryr.png';
import { Box } from '@mui/material';
import "../styles/home.module.css";
import Head from 'next/head';

const NavBarInstance = () => {
    const router = useRouter();
    return (
        <Navbar style={{ padding: "10px", background: "linear-gradient(to bottom, rgba(0, 109, 126, 1) 0%, rgba(1, 103, 119, 1) 21%, rgba(5, 79, 90, 1) 57%, rgba(36, 30, 32, 1) 93%, rgba(36, 30, 32, 1) 100%)" }}>
            <Navbar.Brand href="#" style={{ marginTop: "-20px", fontSize: "30px", color: "orange", fontWeight: 700 }}>QUICKFIX-SI</Navbar.Brand>
            <Nav pullRight>
                <div style={{display:'flex', gap:"2em", color:'white'}}>
                    <h3>Email   Info@QuicKfix-Si.Com</h3>
                    <h3>CALL US: 0722779770</h3>
                    <Button color="cyan" appearance="primary" onClick={() => router.push('user/login')} style={{ marginRight: "10px", borderRadius: "50px" }}>Login to Dashboard</Button>
                </div>
                </Nav>
        </Navbar>
    );
};

const Index = () => {
    const [activeKey, setActiveKey] = React.useState(null);
    return (
        <div>
            <Head>
                <title>Quickfix</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" type="text/css" charSet="UTF-8"
                      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
                <link rel="stylesheet" type="text/css"
                      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
            </Head>
            <NavBarInstance activeKey={activeKey} onSelect={setActiveKey} />
            <Box sx={styles.navbar}>
                    {instance1}
                    {instance2}
                    {instance3}
                    {instance4}
                {instance5}
                {instance6}
            </Box>
            <div style={{ display: "flex", padding: '10px',  background: "#8e8e93" }}>
                <div>
                    <h2 style={{color:"white"}}>Reliable service when
                        you need it the most</h2><br/>
                <Carousel autoplay={true}>
                    <div style={{display:'flex', marginBottom:"-50px"}}>
                        <div style={{marginRight:"20px"}}><Image src={Electrical} alt="electrical" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                        <div style={{marginRight:"20px"}}><Image src={Washing} alt="washing" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                        <div style={{marginRight:"20px"}}><Image src={Cooker} alt="shape right" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                        <div style={{marginRight:"20px"}}><Image src={Dishwasher} alt="shape right" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                    </div>
                    <div style={{display:'flex'}}>
                        <div style={{marginRight:"20px"}}><Image src={Boiler} alt="shape right" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                        <div style={{marginRight:"20px"}}><Image src={Cooler} alt="shape right" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                        <div style={{marginRight:"20px"}}><Image src={Oven} alt="shape right" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                        <div style={{marginRight:"20px"}}><Image src={tumbDryer} alt="shape right" /><h5 style={{color:"white"}}>Electrical works</h5></div>
                    </div>
                    </Carousel>
                </div>
                <div style={{ float: "right" }}>
                    <h3 style={{color:"black"}}>Here to help Keep your
                        appliances working
                    </h3>
                    <Image src={Repair} alt="shape right" width="350" /><Divider/>
                    <center><Button color="cyan" appearance="primary" style={{borderRadius:"50px", padding:"15px"}}>Get Service</Button></center>
                </div>
                </div>
            <Footer />
        </div>
    );
};

export default Index;
const instance1  = (
    <ButtonToolbar >
        <Dropdown icon={<CheckOutlineIcon/>} title="Residential Appliances" trigger="hover" style={{background:"yellow"}}>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Refrigeration and air conditioning">
                <Dropdown.Menu title="Cooker">
                    <Dropdown.Item><img src={Repair} alt="cooker"/></Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Menu title="Fridge">
                    <Dropdown.Item>Fridge Image</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Menu title="Appliances">
                    <Dropdown.Item>Cooker</Dropdown.Item>
                </Dropdown.Menu>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Power Generators ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Kitchen ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Laundry ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Appliances">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Security Systems  ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Audio visuals equipment ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
        </Dropdown>
    </ButtonToolbar>
)
const instance2  = (
    <ButtonToolbar >
        <Dropdown icon={<CheckOutlineIcon/>} title="Commercial Appliances" trigger="hover" style={{background:"yellow"}}>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Refrigeration and air conditioning">
                <Dropdown.Menu title="Item 2-1">
                    <Dropdown.Item>Item 2-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 2-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 2-2</Dropdown.Item>
                <Dropdown.Item>Item 2-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Power Generators ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Kitchen ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Laundry ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Appliances">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Security Systems  ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Audio visuals equipment ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
        </Dropdown>
    </ButtonToolbar>
)
const instance3  = (
    <ButtonToolbar >
        <Dropdown icon={<CheckOutlineIcon/>} title="Hotels & Institutions Appliances" trigger="hover" style={{background:"yellow"}}>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Refrigeration and air conditioning">
                <Dropdown.Menu title="Item 2-1">
                    <Dropdown.Item>Item 2-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 2-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 2-2</Dropdown.Item>
                <Dropdown.Item>Item 2-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Power Generators ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Kitchen ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Laundry ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Appliances">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Security Systems  ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu style={{width:300}} icon={<CheckOutlineIcon/>} title="Audio visuals equipment ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
        </Dropdown>
    </ButtonToolbar>
)
const instance4  = (
    <ButtonToolbar>
        <Dropdown icon={<CheckOutlineIcon/>} title="Building Services" trigger="hover">
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Electrical works ">
                <Dropdown.Menu title="Item 2-1">
                    <Dropdown.Item>Item 2-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 2-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 2-2</Dropdown.Item>
                <Dropdown.Item>Item 2-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Water System and drainage ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Interior works ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Civil works ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Power Generators  ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Security Systems">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Audi visuals equipment ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
        </Dropdown>
    </ButtonToolbar>
)
const instance5  = (
    <ButtonToolbar>
        <Dropdown icon={<CheckOutlineIcon/>} title="Entertainment" trigger="hover">
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Electrical works ">
                <Dropdown.Menu title="Item 2-1">
                    <Dropdown.Item>Item 2-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 2-1-2</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 2-2</Dropdown.Item>
                <Dropdown.Item>Item 2-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Water System and drainage ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Interior works ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Civil works ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Power Generators  ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Security Systems">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Audi visuals equipment ">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
        </Dropdown>
    </ButtonToolbar>
)
const instance6  = (
    <ButtonToolbar>
        <Dropdown icon={<CheckOutlineIcon/>} title="Green Energy" trigger="hover">
            <Dropdown.Item>Item 1</Dropdown.Item>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Right Item 2">
                <Dropdown.Menu title="Item 2-1">
                    <Dropdown.Item>Item 2-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 2-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 2-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 2-2</Dropdown.Item>
                <Dropdown.Item>Item 2-3</Dropdown.Item>
            </Dropdown.Menu>
            <Dropdown.Menu icon={<CheckOutlineIcon/>} title="Left Item 3">
                <Dropdown.Menu title="Item 3-1">
                    <Dropdown.Item>Item 3-1-1</Dropdown.Item>
                    <Dropdown.Item active>Item 3-1-2</Dropdown.Item>
                    <Dropdown.Item>Item 3-1-3</Dropdown.Item>
                </Dropdown.Menu>
                <Dropdown.Item>Item 3-2</Dropdown.Item>
                <Dropdown.Item>Item 3-3</Dropdown.Item>
            </Dropdown.Menu>
        </Dropdown>
    </ButtonToolbar>
)

const styles = {
    navbar: {
        paddingY:"1em",
        paddingX:"5em",
        background: "whitesmoke",
        display: 'flex',
        gap: "2em",
        justifyContent:"center",
    }
}